Public Class Alarm
    Public Property Number As String
    Public Property Name As String
    Public Shared Property Alarms As List(Of Alarm) = New List(Of Alarm)

    ' Constructor to initialize an individual alarm
    Public Sub New(alarmNumber As String, alarmName As String)
        Me.Number = alarmNumber
        Me.Name = alarmName
    End Sub

    ' Method to populate the list with alarms
    Public Shared Sub InitializeAlarms()
        Alarms.Add(New Alarm("0001", "EMERGENCY STOP"))
        Alarms.Add(New Alarm("0002", "X AXIS SERVO ALARM"))
        Alarms.Add(New Alarm("0003", "Y AXIS SERVO ALARM"))
        Alarms.Add(New Alarm("0003", "Z AXIS SERVO ALARM"))
        Alarms.Add(New Alarm("0004", "W AXIS SERVO ALARM"))
        Alarms.Add(New Alarm("0005", "SERVO POWER OFF "))
        Alarms.Add(New Alarm("0006", "SERVO POWER OFF X AXIS "))
        Alarms.Add(New Alarm("0007", "SERVO POWER OFF Y AXIS  "))
        Alarms.Add(New Alarm("0008", "SERVO POWER OFF Z AXIS  "))
        Alarms.Add(New Alarm("0010", "AXIS W IS NOT ON"))
        Alarms.Add(New Alarm("0011", "POSITIONING ERROR MODULE 1 "))
        Alarms.Add(New Alarm("0012", "POSITIONING ERROR MODULE 2 "))
        Alarms.Add(New Alarm("0013", "+ LIMIT X AXIS"))
        Alarms.Add(New Alarm("0014", "- LIMIT X AXIS"))
        Alarms.Add(New Alarm("0015", "X AXIS FORWARD LIMIT"))
        Alarms.Add(New Alarm("0016", "X AXIS REVERSE LIMIT"))
        Alarms.Add(New Alarm("0017", "Z AXIS UPPER LIMIT"))
        Alarms.Add(New Alarm("0018", "Z AXIS LOWER LIMIT"))
        Alarms.Add(New Alarm("0019", "W AXIS FORWARD LIMIT"))
        Alarms.Add(New Alarm("0020", "FIDUCIAL FAILED"))
        Alarms.Add(New Alarm("0021", "LASER MARKER NOT READY"))
        Alarms.Add(New Alarm("0022", "MACHINE DOOR IS OPENED"))
        Alarms.Add(New Alarm("0023", "AIR PRESSOR NOK"))
        Alarms.Add(New Alarm("0024", "SELECT ANY OPERATION MODE"))
        Alarms.Add(New Alarm("0025", "GATE LEFT NOT OPEN"))
        Alarms.Add(New Alarm("0026", "GATE LEFT NOT CLOSED"))
        Alarms.Add(New Alarm("0027", "GATE RIGHT NOT OPEN"))
        Alarms.Add(New Alarm("0028", "GATE RIGHT NOT CLOSED"))
        Alarms.Add(New Alarm("0029", "CONVEYOR WIDTH INPUT ERROR"))
        Alarms.Add(New Alarm("0030", "CONVEYOR IS NOT ON SET VALUE"))
        Alarms.Add(New Alarm("0031", "MACHINE NEED TO INITIALIZE FIRST"))
        Alarms.Add(New Alarm("0032", "AUTO MODE DISABLE"))
        Alarms.Add(New Alarm("0033", "Y AXIS MOVE DISABLED, NEED MOVE X AXIS FIRST"))
        Alarms.Add(New Alarm("0034", "CYCLE INTERRUPTED, PLEASE RESTART AGAIN"))
        Alarms.Add(New Alarm("0035", "LIVE MODE NOT TURNED ON "))
        Alarms.Add(New Alarm("0036", "FIDUCIAL FAILED START NEW CYCLE"))
        Alarms.Add(New Alarm("0037", "FRONT FLIPPER IS NOT IN HOME POSITION"))
        Alarms.Add(New Alarm("0038", "REAR FLIPPER IS NOT IN HOME POSITION"))
        Alarms.Add(New Alarm("0039", "NEED TO MOVE FLIP POSITION FIRST"))
        Alarms.Add(New Alarm("0040", "ALL AXIS SERVO IS OFF"))
        Alarms.Add(New Alarm("0041", "HOME OPERATION UNABLE TO PERFORM BECAUSE PCB IS ALREADY CLAMPED"))
        Alarms.Add(New Alarm("0042", "AUTO OPERATION CAN NOT OPERATE DUE TO PCB IS AVAILABLE ON TRACK"))
        Alarms.Add(New Alarm("0043", "PLC TO LASER COMMUNICATION ERROR"))
        Alarms.Add(New Alarm("0044", "NI TO LASER COMMUNICATION ERROR"))
        Alarms.Add(New Alarm("0045", "PLC TO VISION COMMUNICATION ERROR"))
        Alarms.Add(New Alarm("X101", "Voltage drop in the power "))
        Alarms.Add(New Alarm("X102", "Bus voltage drop"))
        Alarms.Add(New Alarm("X111", "Rotary switch setting error "))
        Alarms.Add(New Alarm("X121", "RAM error 1"))
        Alarms.Add(New Alarm("X122", "RAM error 2"))
        Alarms.Add(New Alarm("X123", "RAM error 3"))
        Alarms.Add(New Alarm("X124", "RAM error 4"))
        Alarms.Add(New Alarm("X125", "RAM error 5"))
        Alarms.Add(New Alarm("X126", "RAM error 6"))
        Alarms.Add(New Alarm("X131", "Clock Error 1"))
        Alarms.Add(New Alarm("X132", "Clock Error 2"))
        Alarms.Add(New Alarm("X133", "Clock Error 3"))
        Alarms.Add(New Alarm("X141", "Control process error 1"))
        Alarms.Add(New Alarm("X142", "Control process error 2"))
        Alarms.Add(New Alarm("X143", "Control process error 3"))
        Alarms.Add(New Alarm("X144", "Control process error 4"))
        Alarms.Add(New Alarm("X145", "Control process error 5"))
        Alarms.Add(New Alarm("X146", "Control process error 6"))
        Alarms.Add(New Alarm("X147", "Control process error 7"))
        Alarms.Add(New Alarm("X148", "Control process error 8"))
        Alarms.Add(New Alarm("X149", "Control process error 9"))
        Alarms.Add(New Alarm("X14A", "Control process error 10"))
        Alarms.Add(New Alarm("X14C", "Control process error 12"))
        Alarms.Add(New Alarm("X14D", "Control process error 13"))
        Alarms.Add(New Alarm("X151", "EEP-ROM error at power on"))
        Alarms.Add(New Alarm("X152", "EEP-ROM error during operation "))
        Alarms.Add(New Alarm("X154", "Home position information read error "))
        Alarms.Add(New Alarm("X161", "Encoder initial communication - Receive data error 1"))
        Alarms.Add(New Alarm("X162", "Encoder initial communication - Receive data error 2"))
        Alarms.Add(New Alarm("X163", "Encoder initial communication - Receive data error 3"))
        Alarms.Add(New Alarm("X165", "Encoder initial communication - Transmission data error 1"))
        Alarms.Add(New Alarm("X166", "Encoder initial communication - Transmission data error 2"))
        Alarms.Add(New Alarm("X167", "Encoder initial communication - Transmission data error 3"))
        Alarms.Add(New Alarm("X16A", "Encoder initial communication - Process error 1"))
        Alarms.Add(New Alarm("X16B", "Encoder initial communication - Process error 2"))
        Alarms.Add(New Alarm("X16C", "Encoder initial communication - Process error 3"))
        Alarms.Add(New Alarm("X16D", "Encoder initial communication - Process error 4"))
        Alarms.Add(New Alarm("X16E", "Encoder initial communication - Process error 5"))
        Alarms.Add(New Alarm("X16F", "Encoder initial communication - Process error 6"))
        Alarms.Add(New Alarm("X171", "Board error 1"))
        Alarms.Add(New Alarm("X173", "Board error 2"))
        Alarms.Add(New Alarm("X174", "Board error 3"))
        Alarms.Add(New Alarm("X175", "Board error 4"))
        Alarms.Add(New Alarm("X176", "Board error 5"))
        Alarms.Add(New Alarm("X177", "Board error 7"))
        Alarms.Add(New Alarm("X191", "Flash-ROM error 1"))
        Alarms.Add(New Alarm("X192", "Flash-ROM error 2"))
        Alarms.Add(New Alarm("X194", "Flash-ROM error 4"))
        Alarms.Add(New Alarm("X195", "Flash-ROM error 5"))
        Alarms.Add(New Alarm("X1A1", "Servo motor combination error 1"))
        Alarms.Add(New Alarm("X1A4", "Servo motor combination error 2"))
        Alarms.Add(New Alarm("X1E1", "Encoder malfunction"))
        Alarms.Add(New Alarm("X1F1", "Incompatible encoder"))
        Alarms.Add(New Alarm("X201", "Encoder normal communication - Receive data error 1"))
        Alarms.Add(New Alarm("X202", "Encoder normal communication - Receive data error 2"))
        Alarms.Add(New Alarm("X203", "Encoder normal communication - Receive data error 3"))
        Alarms.Add(New Alarm("X205", "Encoder normal communication - Transmission data error 1"))
        Alarms.Add(New Alarm("X206", "Encoder normal communication - Transmission data error 2"))
        Alarms.Add(New Alarm("X207", "Encoder normal communication - Transmission data error 3"))
        Alarms.Add(New Alarm("X209", "Encoder normal communication - Receive data error 4"))
        Alarms.Add(New Alarm("X20A", "Encoder normal communication - Receive data error 5"))
        Alarms.Add(New Alarm("X211", "Encoder data error 1"))
        Alarms.Add(New Alarm("X212", "Encoder data update error"))
        Alarms.Add(New Alarm("X213", "Encoder data waveform error"))
        Alarms.Add(New Alarm("X215", "Encoder hardware error 1"))
        Alarms.Add(New Alarm("X216", "Encoder hardware error 2"))
        Alarms.Add(New Alarm("X219", "Encoder data error 2"))
        Alarms.Add(New Alarm("X241", "Ground fault detected at hardware detection circuit"))
        Alarms.Add(New Alarm("X242", "Ground fault detected at software detection function"))
        Alarms.Add(New Alarm("X251", "Servo motor encoder - Absolute position erased"))
        Alarms.Add(New Alarm("X301", "Regenerative heat error"))
        Alarms.Add(New Alarm("X302", "Regeneration signal error"))
        Alarms.Add(New Alarm("X303", "Regeneration feedback signal error"))
        Alarms.Add(New Alarm("X311", "Abnormal motor speed"))
        Alarms.Add(New Alarm("X321", "Overcurrent detected at hardware detection circuit (during operation)"))
        Alarms.Add(New Alarm("X322", "Overcurrent detected at software detection function (during operation)"))
        Alarms.Add(New Alarm("X323", "Overcurrent detected at hardware detection circuit (during a stop)"))
        Alarms.Add(New Alarm("X324", "Overcurrent detected at software detection function (during a stop)"))
        Alarms.Add(New Alarm("X331", "Main circuit voltage error"))
        Alarms.Add(New Alarm("X341", "SSCNET receive data error "))
        Alarms.Add(New Alarm("X342", "SSCNET connector connection error"))
        Alarms.Add(New Alarm("X343", "SSCNET communication data error"))
        Alarms.Add(New Alarm("X344", "Hardware error signal detection"))
        Alarms.Add(New Alarm("X351", "Command frequency error"))
        Alarms.Add(New Alarm("X361", "Continuous communication data error "))
        Alarms.Add(New Alarm("X371", "Parameter setting range error"))
        Alarms.Add(New Alarm("X372", "Parameter combination error"))
        Alarms.Add(New Alarm("X373", "Point table setting error"))
        Alarms.Add(New Alarm("X391", "Program error "))
        Alarms.Add(New Alarm("X392", "Instruction argument external error"))
        Alarms.Add(New Alarm("X393", "Register No. error"))
        Alarms.Add(New Alarm("X394", "Non-correspondence command error"))
        Alarms.Add(New Alarm("X3A1", "Inrush current suppression circuit error"))
        Alarms.Add(New Alarm("X3E1", "Operation mode error"))
        Alarms.Add(New Alarm("X3E6", "Operation mode switch error"))
        Alarms.Add(New Alarm("X451", "Main circuit device overheat error"))
        Alarms.Add(New Alarm("X461", "Abnormal temperature of servo motor 1"))
        Alarms.Add(New Alarm("X465", "Abnormal temperature of servo motor 3"))
        Alarms.Add(New Alarm("X466", "Abnormal temperature of servo motor 4"))
        Alarms.Add(New Alarm("X472", "Cooling fan speed reduction error"))
        Alarms.Add(New Alarm("X501", "Thermal overload error 1 during operation "))
        Alarms.Add(New Alarm("X502", "Thermal overload error 2 during operation "))
        Alarms.Add(New Alarm("X503", "Thermal overload error 4 during operation "))
        Alarms.Add(New Alarm("X504", "Thermal overload error 1 during a stop"))
        Alarms.Add(New Alarm("X505", "Thermal overload error 2 during a stop"))
        Alarms.Add(New Alarm("X506", "Thermal overload error 4 during a stop"))
        Alarms.Add(New Alarm("X511", "Thermal overload error 3 during operation"))
        Alarms.Add(New Alarm("X512", "Thermal overload error 3 during stop"))
        Alarms.Add(New Alarm("X521", "Excess droop pulse 1"))
        Alarms.Add(New Alarm("X523", "Excess droop pulse 2"))
        Alarms.Add(New Alarm("X524", "Error excessive during 0 torque limit"))
        Alarms.Add(New Alarm("X525", "Excess droop pulse 3"))
        Alarms.Add(New Alarm("X541", "Oscillation detection error"))
        Alarms.Add(New Alarm("X562", "Over speed during forced stop"))
        Alarms.Add(New Alarm("X563", "Estimated distance over during forced stop"))
        Alarms.Add(New Alarm("X611", "Point table setting range error"))
        Alarms.Add(New Alarm("X691", "Forward rotation-side software limit detection - Command excess error"))
        Alarms.Add(New Alarm("X692", "Reverse rotation-side software limit detection - Command excess error"))
        Alarms.Add(New Alarm("X693", "Forward rotation stroke end detection - Command excess error"))
        Alarms.Add(New Alarm("X694", "Reverse rotation stroke end detection - Command excess error"))
        Alarms.Add(New Alarm("X861", "Network communication error 1"))
        Alarms.Add(New Alarm("X864", "Network communication error 4"))
        Alarms.Add(New Alarm("X865", "Network communication error 5"))
        Alarms.Add(New Alarm("X8A1", "USB communication time-out error/serial communication time out error"))
        Alarms.Add(New Alarm("X8A2", "Modbus RTU communication time out error"))
        Alarms.Add(New Alarm("X8C1", "Network module communication error 1"))
        Alarms.Add(New Alarm("X8C2", "Network module communication error 2"))
        Alarms.Add(New Alarm("X8C3", "Network module communication error 3"))
        Alarms.Add(New Alarm("X8C4", "Network module communication error 4"))
        Alarms.Add(New Alarm("X8C5", "Network module communication error 5"))
        Alarms.Add(New Alarm("X8C6", "Network module communication error 6"))
        Alarms.Add(New Alarm("X8C7", "Network module communication error 7"))
        Alarms.Add(New Alarm("X8E1", "USB communication receive error/serial communication receive error"))
        Alarms.Add(New Alarm("X8E2", "USB communication checksum error/serial communication checksum error"))
        Alarms.Add(New Alarm("X8E3", "USB communication character error/serial communication character error"))
        Alarms.Add(New Alarm("X8E4", "USB communication command error/serial communication command error"))
        Alarms.Add(New Alarm("X8E5", "USB communication data number  error/serial communication data number error"))
        Alarms.Add(New Alarm("X8E6", "Modbus RTU communication receive error "))
        Alarms.Add(New Alarm("X8E7", "Modbus RTU communication message frame error "))
        Alarms.Add(New Alarm("X8E8", "Modbus RTU communication CRC error "))
        Alarms.Add(New Alarm("X888", "Watchdog"))
        Alarms.Add(New Alarm("X901", "Home position return incomplete"))
        Alarms.Add(New Alarm("X902", "Home position return abnormal termination"))
        Alarms.Add(New Alarm("X905", "Z-phase unpassed"))
        Alarms.Add(New Alarm("X911", "Main circuit device overheat warning"))
        Alarms.Add(New Alarm("X921", "Encoder battery cable disconnection warning"))
        Alarms.Add(New Alarm("X923", "Battery degradation"))
        Alarms.Add(New Alarm("X961", "In-position warning at home positioning"))
        Alarms.Add(New Alarm("X962", "Command input warning at home positioning"))
        Alarms.Add(New Alarm("X963", "Servo off warning at home positioning"))
        Alarms.Add(New Alarm("X971", "Program operation disabled warning"))
        Alarms.Add(New Alarm("X972", "Next station position warning"))
        Alarms.Add(New Alarm("X981", "Forward rotation-side software stroke limit reached"))
        Alarms.Add(New Alarm("X982", "Reverse rotation-side software stroke limit reached"))
        Alarms.Add(New Alarm("X991", "Forward rotation stroke end off"))
        Alarms.Add(New Alarm("X992", "Reverse rotation stroke end off"))
        Alarms.Add(New Alarm("X9B1", "Excess droop pulse 1 warning"))
        Alarms.Add(New Alarm("X9B3", "Excess droop pulse 2 warning"))
        Alarms.Add(New Alarm("X9B4", "Error excessive warning during"))
        Alarms.Add(New Alarm("X9F1", "Low battery"))
        Alarms.Add(New Alarm("XE01", "Excessive regeneration warning"))
        Alarms.Add(New Alarm("XE11", "Thermal overload warning 1 during operation"))
        Alarms.Add(New Alarm("XE12", "Thermal overload warning 2 during operation"))
        Alarms.Add(New Alarm("XE13", "Thermal overload warning 3 during operation"))
        Alarms.Add(New Alarm("XE14", "Thermal overload warning 4 during operation"))
        Alarms.Add(New Alarm("XE15", "Thermal overload warning 1 during a stop"))
        Alarms.Add(New Alarm("XE16", "Thermal overload warning 2 during a stop"))
        Alarms.Add(New Alarm("XE17", "Thermal overload warning 3 during a stop"))
        Alarms.Add(New Alarm("XE18", "Thermal overload warning 4 during a stop"))
        Alarms.Add(New Alarm("XE31", "Multi-revolution counter travel distance excess warning"))
        Alarms.Add(New Alarm("XE32", "Absolute position counter warning"))
        Alarms.Add(New Alarm("XE34", "Absolute positioning counter EEPROM writing frequency warning"))
        Alarms.Add(New Alarm("XE35", "Encoder absolute positioning counter warning"))
        Alarms.Add(New Alarm("XE41", "Parameter setting range error warning"))
        Alarms.Add(New Alarm("XE61", "Forced stop warning"))
        Alarms.Add(New Alarm("XE71", "Controller forced stop input warning"))
        Alarms.Add(New Alarm("XE81", "Decreased cooling fan speed warning"))
        Alarms.Add(New Alarm("XE91", "Servo-on signal on during main circuit off"))
        Alarms.Add(New Alarm("XE92", "Bus voltage drop during low speed operation"))
        Alarms.Add(New Alarm("XE93", "Ready-on signal on during main circuit off"))
        Alarms.Add(New Alarm("XEC1", "Overload warning 2"))
        Alarms.Add(New Alarm("XED1", "Output watt excess warning"))
        Alarms.Add(New Alarm("XF01", "Instantaneous power failure tough drive warning"))
        Alarms.Add(New Alarm("XF03", "Vibration tough drive warning"))
        Alarms.Add(New Alarm("XF21", "Drive recorder - Area writing time out warning"))
        Alarms.Add(New Alarm("XF22", "Drive recorder - Data miswriting warning"))
        Alarms.Add(New Alarm("XF31", "Oscillation detection"))
        Alarms.Add(New Alarm("XF44", "Target position setting range error warning"))
        Alarms.Add(New Alarm("XF46", "Acceleration time constant setting range error warning"))
        Alarms.Add(New Alarm("XF47", "Deceleration time constant setting range error warning"))
        Alarms.Add(New Alarm("XF48", "Control command input error warning"))
        Alarms.Add(New Alarm("XF49", "Home position return type error warning"))
        Alarms.Add(New Alarm("XF51", "Cam data - Area writing time-out warning"))
        Alarms.Add(New Alarm("XF52", "Cam data - Area miswriting warning"))
        Alarms.Add(New Alarm("XF53", "Cam data checksum error"))
        Alarms.Add(New Alarm("XF61", "Cam axis one cycle current value restoration failed"))
        Alarms.Add(New Alarm("XF62", "Cam axis feed current value restoration failed"))
        Alarms.Add(New Alarm("XF63", "Cam unregistered error"))
        Alarms.Add(New Alarm("XF64", "Cam control data setting range error"))
        Alarms.Add(New Alarm("XF65", "Cam No. external error"))
        Alarms.Add(New Alarm("XF66", "Cam control inactive"))
        'HERE START Y AXIS
        Alarms.Add(New Alarm("Y101", "Voltage drop in the power "))
        Alarms.Add(New Alarm("Y102", "Bus voltage drop"))
        Alarms.Add(New Alarm("Y111", "Rotary switch setting error "))
        Alarms.Add(New Alarm("Y121", "RAM error 1"))
        Alarms.Add(New Alarm("Y122", "RAM error 2"))
        Alarms.Add(New Alarm("Y123", "RAM error 3"))
        Alarms.Add(New Alarm("Y124", "RAM error 4"))
        Alarms.Add(New Alarm("Y125", "RAM error 5"))
        Alarms.Add(New Alarm("Y126", "RAM error 6"))
        Alarms.Add(New Alarm("Y131", "Clock Error 1"))
        Alarms.Add(New Alarm("Y132", "Clock Error 2"))
        Alarms.Add(New Alarm("Y133", "Clock Error 3"))
        Alarms.Add(New Alarm("Y141", "Control process error 1"))
        Alarms.Add(New Alarm("Y142", "Control process error 2"))
        Alarms.Add(New Alarm("Y143", "Control process error 3"))
        Alarms.Add(New Alarm("Y144", "Control process error 4"))
        Alarms.Add(New Alarm("Y145", "Control process error 5"))
        Alarms.Add(New Alarm("Y146", "Control process error 6"))
        Alarms.Add(New Alarm("Y147", "Control process error 7"))
        Alarms.Add(New Alarm("Y148", "Control process error 8"))
        Alarms.Add(New Alarm("Y149", "Control process error 9"))
        Alarms.Add(New Alarm("Y14A", "Control process error 10"))
        Alarms.Add(New Alarm("Y14C", "Control process error 12"))
        Alarms.Add(New Alarm("Y14D", "Control process error 13"))
        Alarms.Add(New Alarm("Y151", "EEP-ROM error at power on"))
        Alarms.Add(New Alarm("Y152", "EEP-ROM error during operation "))
        Alarms.Add(New Alarm("Y154", "Home position information read error "))
        Alarms.Add(New Alarm("Y161", "Encoder initial communication - Receive data error 1"))
        Alarms.Add(New Alarm("Y162", "Encoder initial communication - Receive data error 2"))
        Alarms.Add(New Alarm("Y163", "Encoder initial communication - Receive data error 3"))
        Alarms.Add(New Alarm("Y165", "Encoder initial communication - Transmission data error 1"))
        Alarms.Add(New Alarm("Y166", "Encoder initial communication - Transmission data error 2"))
        Alarms.Add(New Alarm("Y167", "Encoder initial communication - Transmission data error 3"))
        Alarms.Add(New Alarm("Y16A", "Encoder initial communication - Process error 1"))
        Alarms.Add(New Alarm("Y16B", "Encoder initial communication - Process error 2"))
        Alarms.Add(New Alarm("Y16C", "Encoder initial communication - Process error 3"))
        Alarms.Add(New Alarm("Y16D", "Encoder initial communication - Process error 4"))
        Alarms.Add(New Alarm("Y16E", "Encoder initial communication - Process error 5"))
        Alarms.Add(New Alarm("Y16F", "Encoder initial communication - Process error 6"))
        Alarms.Add(New Alarm("Y171", "Board error 1"))
        Alarms.Add(New Alarm("Y173", "Board error 2"))
        Alarms.Add(New Alarm("Y174", "Board error 3"))
        Alarms.Add(New Alarm("Y175", "Board error 4"))
        Alarms.Add(New Alarm("Y176", "Board error 5"))
        Alarms.Add(New Alarm("Y177", "Board error 7"))
        Alarms.Add(New Alarm("Y191", "Flash-ROM error 1"))
        Alarms.Add(New Alarm("Y192", "Flash-ROM error 2"))
        Alarms.Add(New Alarm("Y194", "Flash-ROM error 4"))
        Alarms.Add(New Alarm("Y195", "Flash-ROM error 5"))
        Alarms.Add(New Alarm("Y1A1", "Servo motor combination error 1"))
        Alarms.Add(New Alarm("Y1A4", "Servo motor combination error 2"))
        Alarms.Add(New Alarm("Y1E1", "Encoder malfunction"))
        Alarms.Add(New Alarm("Y1F1", "Incompatible encoder"))
        Alarms.Add(New Alarm("Y201", "Encoder normal communication - Receive data error 1"))
        Alarms.Add(New Alarm("Y202", "Encoder normal communication - Receive data error 2"))
        Alarms.Add(New Alarm("Y203", "Encoder normal communication - Receive data error 3"))
        Alarms.Add(New Alarm("Y205", "Encoder normal communication - Transmission data error 1"))
        Alarms.Add(New Alarm("Y206", "Encoder normal communication - Transmission data error 2"))
        Alarms.Add(New Alarm("Y207", "Encoder normal communication - Transmission data error 3"))
        Alarms.Add(New Alarm("Y209", "Encoder normal communication - Receive data error 4"))
        Alarms.Add(New Alarm("Y20A", "Encoder normal communication - Receive data error 5"))
        Alarms.Add(New Alarm("Y211", "Encoder data error 1"))
        Alarms.Add(New Alarm("Y212", "Encoder data update error"))
        Alarms.Add(New Alarm("Y213", "Encoder data waveform error"))
        Alarms.Add(New Alarm("Y215", "Encoder hardware error 1"))
        Alarms.Add(New Alarm("Y216", "Encoder hardware error 2"))
        Alarms.Add(New Alarm("Y219", "Encoder data error 2"))
        Alarms.Add(New Alarm("Y241", "Ground fault detected at hardware detection circuit"))
        Alarms.Add(New Alarm("Y242", "Ground fault detected at software detection function"))
        Alarms.Add(New Alarm("Y251", "Servo motor encoder - Absolute position erased"))
        Alarms.Add(New Alarm("Y301", "Regenerative heat error"))
        Alarms.Add(New Alarm("Y302", "Regeneration signal error"))
        Alarms.Add(New Alarm("Y303", "Regeneration feedback signal error"))
        Alarms.Add(New Alarm("Y311", "Abnormal motor speed"))
        Alarms.Add(New Alarm("Y321", "Overcurrent detected at hardware detection circuit (during operation)"))
        Alarms.Add(New Alarm("Y322", "Overcurrent detected at software detection function (during operation)"))
        Alarms.Add(New Alarm("Y323", "Overcurrent detected at hardware detection circuit (during a stop)"))
        Alarms.Add(New Alarm("Y324", "Overcurrent detected at software detection function (during a stop)"))
        Alarms.Add(New Alarm("Y331", "Main circuit voltage error"))
        Alarms.Add(New Alarm("Y341", "SSCNET receive data error "))
        Alarms.Add(New Alarm("Y342", "SSCNET connector connection error"))
        Alarms.Add(New Alarm("Y343", "SSCNET communication data error"))
        Alarms.Add(New Alarm("Y344", "Hardware error signal detection"))
        Alarms.Add(New Alarm("Y351", "Command frequency error"))
        Alarms.Add(New Alarm("Y361", "Continuous communication data error "))
        Alarms.Add(New Alarm("Y371", "Parameter setting range error"))
        Alarms.Add(New Alarm("Y372", "Parameter combination error"))
        Alarms.Add(New Alarm("Y373", "Point table setting error"))
        Alarms.Add(New Alarm("Y391", "Program error "))
        Alarms.Add(New Alarm("Y392", "Instruction argument external error"))
        Alarms.Add(New Alarm("Y393", "Register No. error"))
        Alarms.Add(New Alarm("Y394", "Non-correspondence command error"))
        Alarms.Add(New Alarm("Y3A1", "Inrush current suppression circuit error"))
        Alarms.Add(New Alarm("Y3E1", "Operation mode error"))
        Alarms.Add(New Alarm("Y3E6", "Operation mode switch error"))
        Alarms.Add(New Alarm("Y451", "Main circuit device overheat error"))
        Alarms.Add(New Alarm("Y461", "Abnormal temperature of servo motor 1"))
        Alarms.Add(New Alarm("Y465", "Abnormal temperature of servo motor 3"))
        Alarms.Add(New Alarm("Y466", "Abnormal temperature of servo motor 4"))
        Alarms.Add(New Alarm("Y472", "Cooling fan speed reduction error"))
        Alarms.Add(New Alarm("Y501", "Thermal overload error 1 during operation "))
        Alarms.Add(New Alarm("Y502", "Thermal overload error 2 during operation "))
        Alarms.Add(New Alarm("Y503", "Thermal overload error 4 during operation "))
        Alarms.Add(New Alarm("Y504", "Thermal overload error 1 during a stop"))
        Alarms.Add(New Alarm("Y505", "Thermal overload error 2 during a stop"))
        Alarms.Add(New Alarm("Y506", "Thermal overload error 4 during a stop"))
        Alarms.Add(New Alarm("Y511", "Thermal overload error 3 during operation"))
        Alarms.Add(New Alarm("Y512", "Thermal overload error 3 during stop"))
        Alarms.Add(New Alarm("Y521", "Excess droop pulse 1"))
        Alarms.Add(New Alarm("Y523", "Excess droop pulse 2"))
        Alarms.Add(New Alarm("Y524", "Error excessive during 0 torque limit"))
        Alarms.Add(New Alarm("Y525", "Excess droop pulse 3"))
        Alarms.Add(New Alarm("Y541", "Oscillation detection error"))
        Alarms.Add(New Alarm("Y562", "Over speed during forced stop"))
        Alarms.Add(New Alarm("Y563", "Estimated distance over during forced stop"))
        Alarms.Add(New Alarm("Y611", "Point table setting range error"))
        Alarms.Add(New Alarm("Y691", "Forward rotation-side software limit detection - Command excess error"))
        Alarms.Add(New Alarm("Y692", "Reverse rotation-side software limit detection - Command excess error"))
        Alarms.Add(New Alarm("Y693", "Forward rotation stroke end detection - Command excess error"))
        Alarms.Add(New Alarm("Y694", "Reverse rotation stroke end detection - Command excess error"))
        Alarms.Add(New Alarm("Y861", "Network communication error 1"))
        Alarms.Add(New Alarm("Y864", "Network communication error 4"))
        Alarms.Add(New Alarm("Y865", "Network communication error 5"))
        Alarms.Add(New Alarm("Y8A1", "USB communication time-out error/serial communication time out error"))
        Alarms.Add(New Alarm("Y8A2", "Modbus RTU communication time out error"))
        Alarms.Add(New Alarm("Y8C1", "Network module communication error 1"))
        Alarms.Add(New Alarm("Y8C2", "Network module communication error 2"))
        Alarms.Add(New Alarm("Y8C3", "Network module communication error 3"))
        Alarms.Add(New Alarm("Y8C4", "Network module communication error 4"))
        Alarms.Add(New Alarm("Y8C5", "Network module communication error 5"))
        Alarms.Add(New Alarm("Y8C6", "Network module communication error 6"))
        Alarms.Add(New Alarm("Y8C7", "Network module communication error 7"))
        Alarms.Add(New Alarm("Y8E1", "USB communication receive error/serial communication receive error"))
        Alarms.Add(New Alarm("Y8E2", "USB communication checksum error/serial communication checksum error"))
        Alarms.Add(New Alarm("Y8E3", "USB communication character error/serial communication character error"))
        Alarms.Add(New Alarm("Y8E4", "USB communication command error/serial communication command error"))
        Alarms.Add(New Alarm("Y8E5", "USB communication data number  error/serial communication data number error"))
        Alarms.Add(New Alarm("Y8E6", "Modbus RTU communication receive error "))
        Alarms.Add(New Alarm("Y8E7", "Modbus RTU communication message frame error "))
        Alarms.Add(New Alarm("Y8E8", "Modbus RTU communication CRC error "))
        Alarms.Add(New Alarm("Y888", "Watchdog"))
        Alarms.Add(New Alarm("Y901", "Home position return incomplete"))
        Alarms.Add(New Alarm("Y902", "Home position return abnormal termination"))
        Alarms.Add(New Alarm("Y905", "Z-phase unpassed"))
        Alarms.Add(New Alarm("Y911", "Main circuit device overheat warning"))
        Alarms.Add(New Alarm("Y921", "Encoder battery cable disconnection warning"))
        Alarms.Add(New Alarm("Y923", "Battery degradation"))
        Alarms.Add(New Alarm("Y961", "In-position warning at home positioning"))
        Alarms.Add(New Alarm("Y962", "Command input warning at home positioning"))
        Alarms.Add(New Alarm("Y963", "Servo off warning at home positioning"))
        Alarms.Add(New Alarm("Y971", "Program operation disabled warning"))
        Alarms.Add(New Alarm("Y972", "Next station position warning"))
        Alarms.Add(New Alarm("Y981", "Forward rotation-side software stroke limit reached"))
        Alarms.Add(New Alarm("Y982", "Reverse rotation-side software stroke limit reached"))
        Alarms.Add(New Alarm("Y991", "Forward rotation stroke end off"))
        Alarms.Add(New Alarm("Y992", "Reverse rotation stroke end off"))
        Alarms.Add(New Alarm("Y9B1", "Excess droop pulse 1 warning"))
        Alarms.Add(New Alarm("Y9B3", "Excess droop pulse 2 warning"))
        Alarms.Add(New Alarm("Y9B4", "Error excessive warning during"))
        Alarms.Add(New Alarm("Y9F1", "Low battery"))
        Alarms.Add(New Alarm("YE01", "Excessive regeneration warning"))
        Alarms.Add(New Alarm("YE11", "Thermal overload warning 1 during operation"))
        Alarms.Add(New Alarm("YE12", "Thermal overload warning 2 during operation"))
        Alarms.Add(New Alarm("YE13", "Thermal overload warning 3 during operation"))
        Alarms.Add(New Alarm("YE14", "Thermal overload warning 4 during operation"))
        Alarms.Add(New Alarm("YE15", "Thermal overload warning 1 during a stop"))
        Alarms.Add(New Alarm("YE16", "Thermal overload warning 2 during a stop"))
        Alarms.Add(New Alarm("YE17", "Thermal overload warning 3 during a stop"))
        Alarms.Add(New Alarm("YE18", "Thermal overload warning 4 during a stop"))
        Alarms.Add(New Alarm("YE31", "Multi-revolution counter travel distance excess warning"))
        Alarms.Add(New Alarm("YE32", "Absolute position counter warning"))
        Alarms.Add(New Alarm("YE34", "Absolute positioning counter EEPROM writing frequency warning"))
        Alarms.Add(New Alarm("YE35", "Encoder absolute positioning counter warning"))
        Alarms.Add(New Alarm("YE41", "Parameter setting range error warning"))
        Alarms.Add(New Alarm("YE61", "Forced stop warning"))
        Alarms.Add(New Alarm("YE71", "Controller forced stop input warning"))
        Alarms.Add(New Alarm("YE81", "Decreased cooling fan speed warning"))
        Alarms.Add(New Alarm("YE91", "Servo-on signal on during main circuit off"))
        Alarms.Add(New Alarm("YE92", "Bus voltage drop during low speed operation"))
        Alarms.Add(New Alarm("YE93", "Ready-on signal on during main circuit off"))
        Alarms.Add(New Alarm("YEC1", "Overload warning 2"))
        Alarms.Add(New Alarm("YED1", "Output watt excess warning"))
        Alarms.Add(New Alarm("YF01", "Instantaneous power failure tough drive warning"))
        Alarms.Add(New Alarm("YF03", "Vibration tough drive warning"))
        Alarms.Add(New Alarm("YF21", "Drive recorder - Area writing time out warning"))
        Alarms.Add(New Alarm("YF22", "Drive recorder - Data miswriting warning"))
        Alarms.Add(New Alarm("YF31", "Oscillation detection"))
        Alarms.Add(New Alarm("YF44", "Target position setting range error warning"))
        Alarms.Add(New Alarm("YF46", "Acceleration time constant setting range error warning"))
        Alarms.Add(New Alarm("YF47", "Deceleration time constant setting range error warning"))
        Alarms.Add(New Alarm("YF48", "Control command input error warning"))
        Alarms.Add(New Alarm("YF49", "Home position return type error warning"))
        Alarms.Add(New Alarm("YF51", "Cam data - Area writing time-out warning"))
        Alarms.Add(New Alarm("YF52", "Cam data - Area miswriting warning"))
        Alarms.Add(New Alarm("YF53", "Cam data checksum error"))
        Alarms.Add(New Alarm("YF61", "Cam axis one cycle current value restoration failed"))
        Alarms.Add(New Alarm("YF62", "Cam axis feed current value restoration failed"))
        Alarms.Add(New Alarm("YF63", "Cam unregistered error"))
        Alarms.Add(New Alarm("YF64", "Cam control data setting range error"))
        Alarms.Add(New Alarm("YF65", "Cam No. external error"))
        Alarms.Add(New Alarm("YF66", "Cam control inactive"))
    End Sub

    ' Override ToString for easy display
    Public Overrides Function ToString() As String
        Return $"{Number}: {Name}"
    End Function
End Class
